apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-p5-odcr-vpc
  region: ap-northeast-1
  version: "1.29"

# Substitute vpc and subnet ids below
vpc:
  id: vpc-07437304aa261570e
  subnets:
    private:
      private-one:
        id: subnet-0f776e34fe5314fa7
      private-two:
        id: subnet-0607e49a8a67aca72
    public:
      public-one:
        id: subnet-07b90d484a538dcb5
      public-two:
        id: subnet-0c2dc355558438f2f

# Fully-managed nodegroups     
managedNodeGroups:

    # GPU nodegroup
    # Update capacityReservationID below
  - name: p5-ocdr
    instanceType: p5.48xlarge
    instancePrefix: p5-odcr-nodes
    privateNetworking: true
    efaEnabled: true
    minSize: 16
    desiredCapacity: 16
    maxSize: 16
    volumeSize: 1024
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "cr-03d3df2e13babf2ae"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true

      